test_add (lianshou.program.test_hello.TestHello) ... ok
test_say_hello (lianshou.program.test_hello.TestHello) ... ok
test_one_equation (lianshou.program.test_fk_math.TestFkMath) ... FAIL
test_two_equation (lianshou.program.test_fk_math.TestFkMath) ... ok

======================================================================
FAIL: test_one_equation (lianshou.program.test_fk_math.TestFkMath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\python\framework\lianshou\program\test_fk_math.py", line 11, in test_one_equation
    self.assertTrue(fk_math.one_equation(4, 10) == -2.5, .00001)
AssertionError: False is not true : 1e-05

----------------------------------------------------------------------
Ran 4 tests in 0.000s

FAILED (failures=1)
